export const initialEdges = [
    // root -> 2nd layer categories
    {id: "e-root-1", source: "context-factors", target: "technical-characteristics", type: "straight"},
    {id: "e-root-2", source: "context-factors", target: "data-governance", type: "straight"},
    {id: "e-root-3", source: "context-factors", target: "human-factors", type: "straight"},
    {id: "e-root-4", source: "context-factors", target: "market-phase", type: "straight"},
    {id: "e-root-5", source: "context-factors", target: "legal-interactions", type: "straight"},
    {id: "e-root-6", source: "context-factors", target: "provider-context", type: "straight"},
    {id: "e-root-7", source: "context-factors", target: "financial-sector", type: "straight"},
    {id: "e-root-8", source: "context-factors", target: "risk-assessment", type: "straight"},
    {id: "e-root-9", source: "context-factors", target: "conformity-assessment", type: "straight"},
    {id: "e-root-10", source: "context-factors", target: "supply-chain", type: "straight"},
    {id: "e-root-11", source: "context-factors", target: "operational-control", type: "straight"},
    {id: "e-root-12", source: "context-factors", target: "authorities-oversight", type: "straight"},
    {id: "e-root-13", source: "context-factors", target: "post-market-monitoring", type: "straight"},
    {id: "e-root-14", source: "context-factors", target: "role-changes-system-modification", type: "straight"},
    {id: "e-root-15", source: "context-factors", target: "third-party-ecosystem-dependencies", type: "straight"},
    {id: "e-root-16", source: "context-factors", target: "deployer-context-responsibilities", type: "straight"},
    {id: "e-root-17", source: "context-factors", target: "use-case-application-context", type: "straight"},
    {id: "e-root-18", source: "context-factors", target: "transparency-user-interaction", type: "straight"},
    {id: "e-root-19", source: "context-factors", target: "law-enforcement-special-regimes", type: "straight"},
    {id: "e-root-20", source: "context-factors", target: "assessment-reuse-existing-evaluations", type: "straight"},
    {id: "e-root-21", source: "context-factors", target: "user-role", type: "straight"},

    // 2nd layer categories -> 3rd layer CF nodes
    {id: "e-cf-1", source: "technical-characteristics", target: "cf-8-1", type: "straight"},
    {id: "e-cf-2", source: "technical-characteristics", target: "cf-8-3", type: "straight"},
    {id: "e-cf-3", source: "technical-characteristics", target: "cf-10-1", type: "straight"},
    {id: "e-cf-4", source: "technical-characteristics", target: "cf-13-1", type: "straight"},
    {id: "e-cf-5", source: "technical-characteristics", target: "cf-13-3", type: "straight"},
    {id: "e-cf-6", source: "technical-characteristics", target: "cf-14-1", type: "straight"},
    {id: "e-cf-7", source: "technical-characteristics", target: "cf-14-3", type: "straight"},
    {id: "e-cf-8", source: "technical-characteristics", target: "cf-14-5", type: "straight"},
    {id: "e-cf-9", source: "technical-characteristics", target: "cf-15-1", type: "straight"},
    {id: "e-cf-10", source: "technical-characteristics", target: "cf-15-2", type: "straight"},
    {id: "e-cf-11", source: "technical-characteristics", target: "cf-15-4", type: "straight"},
    {id: "e-cf-12", source: "data-governance", target: "cf-10-2", type: "straight"},
    {id: "e-cf-13", source: "data-governance", target: "cf-10-3", type: "straight"},
    {id: "e-cf-14", source: "data-governance", target: "cf-19-2", type: "straight"},
    {id: "e-cf-15", source: "data-governance", target: "cf-26-10", type: "straight"},
    {id: "e-cf-16", source: "human-factors", target: "cf-9-3", type: "straight"},
    {id: "e-cf-17", source: "human-factors", target: "cf-9-5", type: "straight"},
    {id: "e-cf-18", source: "human-factors", target: "cf-10-5", type: "straight"},
    {id: "e-cf-19", source: "human-factors", target: "cf-13-2", type: "straight"},
    {id: "e-cf-20", source: "human-factors", target: "cf-13-4", type: "straight"},
    {id: "e-cf-21", source: "human-factors", target: "cf-14-2", type: "straight"},
    {id: "e-cf-22", source: "human-factors", target: "cf-27-6", type: "straight"},
    {id: "e-cf-23", source: "market-phase", target: "cf-9-1", type: "straight"},
    {id: "e-cf-24", source: "market-phase", target: "cf-11-2", type: "straight"},
    {id: "e-cf-25", source: "market-phase", target: "cf-12-2", type: "straight"},
    {id: "e-cf-26", source: "market-phase", target: "cf-16-2", type: "straight"},
    {id: "e-cf-27", source: "market-phase", target: "cf-17-5", type: "straight"},
    {id: "e-cf-28", source: "market-phase", target: "cf-18-3", type: "straight"},
    {id: "e-cf-29", source: "legal-interactions", target: "cf-8-2", type: "straight"},
    {id: "e-cf-30", source: "legal-interactions", target: "cf-9-4", type: "straight"},
    {id: "e-cf-31", source: "legal-interactions", target: "cf-11-3", type: "straight"},
    {id: "e-cf-32", source: "legal-interactions", target: "cf-16-3", type: "straight"},
    {id: "e-cf-33", source: "legal-interactions", target: "cf-17-2", type: "straight"},
    {id: "e-cf-34", source: "legal-interactions", target: "cf-17-4", type: "straight"},
    {id: "e-cf-35", source: "provider-context", target: "cf-11-1", type: "straight"},
    {id: "e-cf-36", source: "provider-context", target: "cf-17-1", type: "straight"},
    {id: "e-cf-37", source: "provider-context", target: "cf-18-4", type: "straight"},
    {id: "e-cf-38", source: "provider-context", target: "cf-22-1", type: "straight"},
    {id: "e-cf-39", source: "financial-sector", target: "cf-17-3", type: "straight"},
    {id: "e-cf-40", source: "financial-sector", target: "cf-18-2", type: "straight"},
    {id: "e-cf-41", source: "financial-sector", target: "cf-19-3", type: "straight"},
    {id: "e-cf-42", source: "financial-sector", target: "cf-26-5", type: "straight"},
    {id: "e-cf-43", source: "risk-assessment", target: "cf-9-2", type: "straight"},
    {id: "e-cf-44", source: "risk-assessment", target: "cf-15-3", type: "straight"},
    {id: "e-cf-45", source: "risk-assessment", target: "cf-20-2", type: "straight"},
    {id: "e-cf-46", source: "risk-assessment", target: "cf-23-3", type: "straight"},
    {id: "e-cf-47", source: "risk-assessment", target: "cf-24-2", type: "straight"},
    {id: "e-cf-48", source: "risk-assessment", target: "cf-26-9", type: "straight"},
    {id: "e-cf-49", source: "conformity-assessment", target: "cf-16-4", type: "straight"},
    {id: "e-cf-50", source: "conformity-assessment", target: "cf-18-1", type: "straight"},
    {id: "e-cf-51", source: "conformity-assessment", target: "cf-20-1", type: "straight"},
    {id: "e-cf-52", source: "conformity-assessment", target: "cf-22-2", type: "straight"},
    {id: "e-cf-53", source: "conformity-assessment", target: "cf-23-2", type: "straight"},
    {id: "e-cf-54", source: "supply-chain", target: "cf-20-4", type: "straight"},
    {id: "e-cf-55", source: "supply-chain", target: "cf-23-1", type: "straight"},
    {id: "e-cf-56", source: "supply-chain", target: "cf-24-1", type: "straight"},
    {id: "e-cf-57", source: "supply-chain", target: "cf-24-5", type: "straight"},
    {id: "e-cf-58", source: "operational-control", target: "cf-16-1", type: "straight"},
    {id: "e-cf-59", source: "operational-control", target: "cf-19-1", type: "straight"},
    {id: "e-cf-60", source: "operational-control", target: "cf-21-1", type: "straight"},
    {id: "e-cf-61", source: "operational-control", target: "cf-22-3", type: "straight"},
    {id: "e-cf-62", source: "operational-control", target: "cf-26-2", type: "straight"},
    {id: "e-cf-63", source: "operational-control", target: "cf-26-1", type: "straight"},
    {id: "e-cf-64", source: "authorities-oversight", target: "cf-21-2", type: "straight"},
    {id: "e-cf-65", source: "authorities-oversight", target: "cf-21-3", type: "straight"},
    {id: "e-cf-66", source: "post-market-monitoring", target: "cf-20-3", type: "straight"},
    {id: "e-cf-67", source: "post-market-monitoring", target: "cf-20-5", type: "straight"},
    {id: "e-cf-68", source: "role-changes-system-modification", target: "cf-25-1", type: "straight"},
    {id: "e-cf-69", source: "role-changes-system-modification", target: "cf-25-2", type: "straight"},
    {id: "e-cf-70", source: "role-changes-system-modification", target: "cf-25-3", type: "straight"},
    {id: "e-cf-71", source: "role-changes-system-modification", target: "cf-25-4", type: "straight"},
    {id: "e-cf-72", source: "third-party-ecosystem-dependencies", target: "cf-25-5", type: "straight"},
    {id: "e-cf-73", source: "third-party-ecosystem-dependencies", target: "cf-25-6", type: "straight"},
    {id: "e-cf-74", source: "third-party-ecosystem-dependencies", target: "cf-25-7", type: "straight"},
    {id: "e-cf-75", source: "deployer-context-responsibilities", target: "cf-26-3", type: "straight"},
    {id: "e-cf-76", source: "deployer-context-responsibilities", target: "cf-26-4", type: "straight"},
    {id: "e-cf-77", source: "deployer-context-responsibilities", target: "cf-26-8", type: "straight"},
    {id: "e-cf-78", source: "deployer-context-responsibilities", target: "cf-27-1", type: "straight"},
    {id: "e-cf-79", source: "use-case-application-context", target: "cf-10-4", type: "straight"},
    {id: "e-cf-80", source: "use-case-application-context", target: "cf-26-6", type: "straight"},
    {id: "e-cf-81", source: "use-case-application-context", target: "cf-26-7", type: "straight"},
    {id: "e-cf-82", source: "transparency-user-interaction", target: "cf-50-1", type: "straight"},
    {id: "e-cf-83", source: "transparency-user-interaction", target: "cf-50-2", type: "straight"},
    {id: "e-cf-84", source: "transparency-user-interaction", target: "cf-50-3", type: "straight"},
    {id: "e-cf-85", source: "transparency-user-interaction", target: "cf-50-4", type: "straight"},
    {id: "e-cf-86", source: "transparency-user-interaction", target: "cf-50-5", type: "straight"},
    {id: "e-cf-87", source: "transparency-user-interaction", target: "cf-50-7", type: "straight"},
    {id: "e-cf-88", source: "transparency-user-interaction", target: "cf-50-8", type: "straight"},
    {id: "e-cf-89", source: "transparency-user-interaction", target: "cf-50-9", type: "straight"},
    {id: "e-cf-90", source: "law-enforcement-special-regimes", target: "cf-50-6", type: "straight"},
    {id: "e-cf-91", source: "assessment-reuse-existing-evaluations", target: "cf-27-2", type: "straight"},
    {id: "e-cf-92", source: "assessment-reuse-existing-evaluations", target: "cf-27-3", type: "straight"},
    {id: "e-cf-93", source: "assessment-reuse-existing-evaluations", target: "cf-27-4", type: "straight"},
    {id: "e-cf-94", source: "assessment-reuse-existing-evaluations", target: "cf-27-5", type: "straight"},
    {id: "e-cf-95", source: "user-role", target: "provider", type: "straight"},
    {id: "e-cf-96", source: "user-role", target: "deployer", type: "straight"},

    // final layer
    {
        id: "phase-one-result",
        type: "hexagon",
        position: {x: 2125, y: 1500},
        draggable: true,
    },
]
