export const initialEdges = [
    {id: "e1", source: "context-factors", target: "cf-9-1"},
    {id: "e2", source: "context-factors", target: "cf-9-2"},
    {id: "e3", source: "context-factors", target: "cf-9-3"},
    {id: "e4", source: "context-factors", target: "cf-9-4"},
    {id: "e5", source: "context-factors", target: "cf-10-1"},
    {id: "e6", source: "context-factors", target: "cf-10-2"},
    {id: "e7", source: "context-factors", target: "cf-10-3"},
    {id: "e8", source: "context-factors", target: "cf-13-1"},
    {id: "e9", source: "context-factors", target: "cf-13-2"},
    {id: "e10", source: "context-factors", target: "cf-13-3"},
    {id: "e11", source: "context-factors", target: "cf-14-1"},
    {id: "e12", source: "context-factors", target: "cf-14-2"},
    {id: "e13", source: "context-factors", target: "cf-14-3"},
    {id: "e14", source: "context-factors", target: "cf-14-4"},
    {id: "e15", source: "context-factors", target: "cf-15-1"},
    {id: "e16", source: "context-factors", target: "cf-15-2"},
    {id: "e17", source: "context-factors", target: "cf-15-3"},
    {id: "e18", source: "context-factors", target: "cf-15-4"},
    {id: "e19", source: "context-factors", target: "cf-15-5"},
    {id: "e20", source: "context-factors", target: "cf-15-6"},
    {id: "e21", source: "context-factors", target: "cf-15-7"},
];
